id: I0D0DF318
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T03:58:28+00:00'
last_modified: '2022-06-08T02:17:00.526187+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17577
  title: ཁྲི་ཆེན་སྤྲུལ་སྐུ་བློ་བཟང་འཇམ་དཔལ་བསྟན་འཛིན་སེང་གེའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    94FB:
      image_group_id: I8LS17583
      title: ''
      total_pages: 80
      order: 1
      base_file: 94FB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
