id: P004608
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17577
  title: ཁྲི་ཆེན་སྤྲུལ་སྐུ་བློ་བཟང་འཇམ་དཔལ་བསྟན་འཛིན་སེང་གེའི་རྣམ་ཐར།
  author: ''
  volumes:
    4cafd6308faa4f1293cf6ac0e033670c:
      image_group_id: I8LS17583
      title: ''
      volume_number: 1
      total_pages: 80
